from pathlib import Path

p = Path("crates/prospect-commercial/src/lib.rs")
s = p.read_text()

old = 'use std::cmp::Reverse;\n'
new = 'use std::cmp::{Ordering, Reverse};\n'
if old in s:
    s = s.replace(old, new, 1)
elif new not in s:
    raise SystemExit("cmp import anchor missing")

old = '''/// Conservative lexicographic policy: improve lower-tail mean first, then\n/// expected net cash when the downside score ties.\n#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]\npub struct DownsideFirst;\n\nimpl DecisionPolicy<CommercialRiskSignature> for DownsideFirst {\n    type Score = (i128, i128);\n\n    fn utility(&self, signature: &CommercialRiskSignature) -> Self::Score {\n        (\n            signature.downside_tail_mean_minor_floor,\n            signature.expected_net_cash_weighted_minor_ppm,\n        )\n    }\n}\n'''
new = '''/// Exact lexicographic score used by [`DownsideFirst`].\n///\n/// The downside mean is retained as its exact rational numerator/denominator\n/// pair so sub-minor-unit differences are not erased before the expected-value\n/// tie-break. A zero denominator can only arise from a manually fabricated\n/// signature and is ranked below every validated signature.\n#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub struct DownsideFirstScore {\n    downside_tail_weighted_minor_ppm: i128,\n    downside_tail_ppm: u32,\n    expected_net_cash_weighted_minor_ppm: i128,\n}\n\nimpl Ord for DownsideFirstScore {\n    fn cmp(&self, other: &Self) -> Ordering {\n        compare_exact_downside_means(\n            self.downside_tail_weighted_minor_ppm,\n            self.downside_tail_ppm,\n            other.downside_tail_weighted_minor_ppm,\n            other.downside_tail_ppm,\n        )\n        .then_with(|| {\n            self.expected_net_cash_weighted_minor_ppm\n                .cmp(&other.expected_net_cash_weighted_minor_ppm)\n        })\n    }\n}\n\nimpl PartialOrd for DownsideFirstScore {\n    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {\n        Some(self.cmp(other))\n    }\n}\n\nfn compare_exact_downside_means(\n    left_weighted: i128,\n    left_tail_ppm: u32,\n    right_weighted: i128,\n    right_tail_ppm: u32,\n) -> Ordering {\n    match (left_tail_ppm, right_tail_ppm) {\n        (0, 0) => return left_weighted.cmp(&right_weighted),\n        (0, _) => return Ordering::Less,\n        (_, 0) => return Ordering::Greater,\n        _ => {}\n    }\n\n    let left_denominator = i128::from(left_tail_ppm);\n    let right_denominator = i128::from(right_tail_ppm);\n    let left_integer = left_weighted.div_euclid(left_denominator);\n    let right_integer = right_weighted.div_euclid(right_denominator);\n    match left_integer.cmp(&right_integer) {\n        Ordering::Equal => {\n            let left_remainder = left_weighted.rem_euclid(left_denominator);\n            let right_remainder = right_weighted.rem_euclid(right_denominator);\n            (left_remainder * right_denominator).cmp(&(right_remainder * left_denominator))\n        }\n        ordering => ordering,\n    }\n}\n\n/// Conservative lexicographic policy: improve the exact lower-tail mean first,\n/// then expected net cash only when the exact downside means tie.\n#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]\npub struct DownsideFirst;\n\nimpl DecisionPolicy<CommercialRiskSignature> for DownsideFirst {\n    type Score = DownsideFirstScore;\n\n    fn utility(&self, signature: &CommercialRiskSignature) -> Self::Score {\n        DownsideFirstScore {\n            downside_tail_weighted_minor_ppm: signature.downside_tail_weighted_minor_ppm,\n            downside_tail_ppm: signature.downside_tail_ppm,\n            expected_net_cash_weighted_minor_ppm: signature.expected_net_cash_weighted_minor_ppm,\n        }\n    }\n}\n'''
if old in s:
    s = s.replace(old, new, 1)
elif new not in s:
    raise SystemExit("DownsideFirst anchor missing")

anchor = '''    #[test]\n    fn policies_expose_distinct_commercial_preferences() {\n'''
test = '''    #[test]\n    fn downside_first_preserves_sub_minor_tail_ordering() {\n        let worse = CommercialRiskSignature {\n            expected_net_cash_weighted_minor_ppm: 10 * i128::from(PROBABILITY_SCALE_PPM),\n            expected_net_cash_minor_floor: 10,\n            loss_probability_ppm: 0,\n            worst_case_net_cash_minor: 0,\n            best_case_net_cash_minor: 10,\n            downside_tail_ppm: 600_000,\n            downside_tail_weighted_minor_ppm: 0,\n            downside_tail_mean_minor_floor: 0,\n        };\n        let better = CommercialRiskSignature {\n            expected_net_cash_weighted_minor_ppm: 0,\n            expected_net_cash_minor_floor: 0,\n            loss_probability_ppm: 0,\n            worst_case_net_cash_minor: 0,\n            best_case_net_cash_minor: 1,\n            downside_tail_ppm: 600_000,\n            downside_tail_weighted_minor_ppm: 300_000,\n            downside_tail_mean_minor_floor: 0,\n        };\n\n        assert_eq!(worse.downside_tail_mean_minor_floor, better.downside_tail_mean_minor_floor);\n        assert!(DownsideFirst.utility(&better) > DownsideFirst.utility(&worse));\n    }\n\n    #[test]\n    fn downside_first_compares_exact_means_across_tail_masses() {\n        let half_at_six_tenths = DownsideFirstScore {\n            downside_tail_weighted_minor_ppm: 300_000,\n            downside_tail_ppm: 600_000,\n            expected_net_cash_weighted_minor_ppm: 1,\n        };\n        let half_at_eight_tenths = DownsideFirstScore {\n            downside_tail_weighted_minor_ppm: 400_000,\n            downside_tail_ppm: 800_000,\n            expected_net_cash_weighted_minor_ppm: 2,\n        };\n        let just_below_half = DownsideFirstScore {\n            downside_tail_weighted_minor_ppm: 399_999,\n            downside_tail_ppm: 800_000,\n            expected_net_cash_weighted_minor_ppm: i128::MAX,\n        };\n\n        assert!(half_at_eight_tenths > half_at_six_tenths);\n        assert!(half_at_six_tenths > just_below_half);\n    }\n\n'''
if anchor in s and test not in s:
    s = s.replace(anchor, test + anchor, 1)
elif test not in s:
    raise SystemExit("test anchor missing")

p.write_text(s)
